### PR TITLE
GadgetronImageWrap::order()

### PR DESCRIPTION
**Pull request by rijobro**
This addresses #262. Sort so that contrast varies slowest, then repetition and then lastly sort by dot product between `position` and `slice_dir`.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Should [AcquisitionData::order](https://github.com/CCPPETMR/SIRF/blob/029f1f2e8890cc1cb22815507948b652f08cb1ad/src/xGadgetron/cGadgetron/gadgetron_data_containers.cpp#L563) include contrast as well?

**Comment by DANAJK** [comment]
It wasn't clear to us if we should sort on all the possible parameters, e.g. contrast, or not. I assume that for parameters that are not sorted, the natural order will be the temporal order of acquisition and this seems like a reasonable way to leave it.

**Comment by KrisThielemans** [comment]
makes sense to me

**Comment by KrisThielemans** [comment]
> I'd suggest adding also the head.phase

agreed. let's then merge this

**Comment by rijobro** [comment]
Already done.

**Pull request merged**
