### PR TITLE
SIRFReg - missing symbol

### PR DESCRIPTION
**Pull request by ashgillman**
See discussion in #230 
Relates to SIRFReg only #211

### CODE REVIEW

**Comment by ashgillman** [comment]
I showed in the other thread:

```
$ nm /home/gil2a4/dev/CCPPETMR@github.com/SIRF/install/python/sirf/_pysirfreg.so | grep InterfileHeader      
                 U _ZN4stir15InterfileHeaderC1Ev
00000000001f53b0 W _ZN4stir15InterfileHeaderD0Ev
00000000001f4e60 W _ZN4stir15InterfileHeaderD1Ev
00000000001f4e60 W _ZN4stir15InterfileHeaderD2Ev
00000000001f4bd0 W _ZN4stir22MinimalInterfileHeaderD0Ev
00000000001f4af0 W _ZN4stir22MinimalInterfileHeaderD1Ev
00000000001f4af0 W _ZN4stir22MinimalInterfileHeaderD2Ev
                 U _ZNK4stir22MinimalInterfileHeader17get_exam_info_ptrEv
00000000006a8a98 V _ZTIN4stir22MinimalInterfileHeaderE
0000000000446160 V _ZTSN4stir22MinimalInterfileHea$ nm /home/gil2a4/dev/CCPPETMR@github.com/SIRF/install/python/sirf/_pysirfreg.so | grep InterfileHeader      
                 U _ZN4stir15InterfileHeaderC1Ev
00000000001f53b0 W _ZN4stir15InterfileHeaderD0Ev
00000000001f4e60 W _ZN4stir15InterfileHeaderD1Ev
00000000001f4e60 W _ZN4stir15InterfileHeaderD2Ev
00000000001f4bd0 W _ZN4stir22MinimalInterfileHeaderD0Ev
00000000001f4af0 W _ZN4stir22MinimalInterfileHeaderD1Ev
00000000001f4af0 W _ZN4stir22MinimalInterfileHeaderD2Ev
                 U _ZNK4stir22MinimalInterfileHeader17get_exam_info_ptrEv
00000000006a8a98 V _ZTIN4stir22MinimalInterfileHeaderE
0000000000446160 V _ZTSN4stir22MinimalInterfileHeaderE
                 U _ZTVN4stir15InterfileHeaderE
00000000006a8ab0 V _ZTVN4stir22MinimalInterfileHeaderE
derE
                 U _ZTVN4stir15InterfileHeaderE
00000000006a8ab0 V _ZTVN4stir22MinimalInterfileHeaderE
```

But interestingly:

```
$ nm /home/gil2a4/dev/CCPPETMR@github.com/SIRF/install/python/sirf/_pystir.so | grep InterfileHeader         
0000000000183d00 t _GLOBAL__sub_I_InterfileHeader.cxx                                                                                                        
0000000000183d60 t _GLOBAL__sub_I_InterfileHeaderSiemens.cxx
00000000003135f0 T _ZN4stir15InterfileHeader15post_processingEv
0000000000318dc0 T _ZN4stir15InterfileHeader16read_frames_infoEv
00000000003151a0 T _ZN4stir15InterfileHeader16read_matrix_infoEv
0000000000314a90 T _ZN4stir15InterfileHeader16set_type_of_dataEv
0000000000315640 T _ZN4stir15InterfileHeaderC1Ev
0000000000315640 T _ZN4stir15InterfileHeaderC2Ev
000000000021b680 W _ZN4stir15InterfileHeaderD0Ev
000000000021b480 W _ZN4stir15InterfileHeaderD1Ev
000000000021b480 W _ZN4stir15InterfileHeaderD2Ev
0000000000320970 T _ZN4stir22InterfileHeaderSiemens15post_processingEv
0000000000321430 T _ZN4stir22InterfileHeaderSiemens16set_type_of_dataEv
00000000003217e0 T _ZN4stir22InterfileHeaderSiemensC1Ev
00000000003217e0 T _ZN4stir22InterfileHeaderSiemensC2Ev
0000000000327150 W _ZN4stir22InterfileHeaderSiemensD0Ev
0000000000327e80 W _ZN4stir22InterfileHeaderSiemensD1Ev
0000000000327e80 W _ZN4stir22InterfileHeaderSiemensD2Ev
00000000004c62a0 R _ZN4stir22MinimalInterfileHeader20double_value_not_setE
0000000000313eb0 T _ZN4stir22MinimalInterfileHeader20set_imaging_modalityEv
0000000000314410 T _ZN4stir22MinimalInterfileHeaderC1Ev
0000000000314410 T _ZN4stir22MinimalInterfileHeaderC2Ev
000000000021b400 W _ZN4stir22MinimalInterfileHeaderD0Ev
000000000021b160 W _ZN4stir22MinimalInterfileHeaderD1Ev
000000000021b160 W _ZN4stir22MinimalInterfileHeaderD2Ev
000000000031cfd0 W _ZNK4stir15InterfileHeader18get_num_data_typesEv                                                                                          
0000000000314220 T _ZNK4stir22MinimalInterfileHeader17get_exam_info_ptrEv                                                                                    
0000000000314230 T _ZNK4stir22MinimalInterfileHeader18get_exam_info_sptrEv
00000000007532e8 V _ZTIN4stir15InterfileHeaderE                                                                                                              
00000000007534f8 V _ZTIN4stir22InterfileHeaderSiemensE                                                                                                       
000000000074cfe8 V _ZTIN4stir22MinimalInterfileHeaderE
00000000004c6240 V _ZTSN4stir15InterfileHeaderE                                                                                                              
00000000004c6c80 V _ZTSN4stir22InterfileHeaderSiemensE                                                                                                       
00000000004b7aa0 V _ZTSN4stir22MinimalInterfileHeaderE
0000000000753330 V _ZTVN4stir15InterfileHeaderE                                                                                                              
0000000000753558 V _ZTVN4stir22InterfileHeaderSiemensE                                                                                                       
000000000074d298 V _ZTVN4stir22MinimalInterfileHeaderE
```

Not undefined here.

I guess we'd expect them to be defined based on the existing transitive dependencies:
- pysirfreg -> SIRFReg
- SIRFReg -> cstir
- cstir -> ${STIR_LIBRARIES}

https://github.com/CCPPETMR/SIRF/blob/daed8676e9ee2ea06478b58c75817869f0350812/src/Registration/pReg/CMakeLists.txt#L34

https://github.com/CCPPETMR/SIRF/blob/daed8676e9ee2ea06478b58c75817869f0350812/src/Registration/cReg/CMakeLists.txt#L35

https://github.com/CCPPETMR/SIRF/blob/daed8676e9ee2ea06478b58c75817869f0350812/src/xSTIR/cSTIR/CMakeLists.txt#L32

**Comment by ashgillman** [comment]
```
[ 39%] Linking CXX shared module _pystir.so                                                                                                                  
[ 48%] Built target _pystir                                                                                                                                  
[ 49%] Linking CXX executable test4                                                                                                                          
[ 57%] Built target test4                                                                                                                                    
[ 59%] Linking CXX static library libSIRFReg.a                                                                                                               
[ 72%] Built target SIRFReg                                                                                                                                  
[ 73%] Linking CXX shared module _pysirfreg.so 
```

I'm guessing something here in the mixing of static and shared?

**Comment by ashgillman** [comment]
The following diff did not work for me:

```
@@ -31,7 +31,7 @@ if(BUILD_PYTHON)
   INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_PATH})
   SET(SWIG_MODULE_pysirfreg_EXTRA_DEPS "${cSIRFREG_INCLUDE_DIR}/csirfreg.h")
   SWIG_ADD_MODULE(pysirfreg python pysirfreg.i)
-  SWIG_LINK_LIBRARIES(pysirfreg SIRFReg ${PYTHON_LIBRARIES} ${STIR_LIBRARIES})
+  SWIG_LINK_LIBRARIES(pysirfreg SIRFReg ${PYTHON_LIBRARIES} cstir)
 
   include_directories(${PROJECT_SOURCE_DIR}/src/common/include)
```

Only directly linking STIR_LIBRARIES for some reason...

**Comment by KrisThielemans** [comment]
Please do a verbose build and check

**Pull request merged**
