### PR TITLE
no functions in matlab scripts

### PR DESCRIPTION
**Pull request by rijobro**

### CODE REVIEW

**Comment by evgueni-ovtchinnikov** [comment]
`test_mReg` throws
```
Error using sirf.Reg.ImageWeightedMean
Error: File: ImageWeightedMean.m Line: 50 Column: 23
The input character is not valid in MATLAB statements or expressions.

Error in test_mReg (line 670)
		wm1 = sirf.Reg.ImageWeightedMean();
```
because of " used in line 50 of ImageWeightedMean.m (must be ')

**Comment by rijobro** [comment]
> because of " used in line 50 of ImageWeightedMean.m (must be ')

Just changed. Could you give it a go now?

**Comment by evgueni-ovtchinnikov** [comment]
i did already before commenting (edited that line myself) to make sure it works now

btw why not put folder results in mReg/test in .gitignore?

**Comment by rijobro** [comment]
> btw why not put folder results in mReg/test in .gitignore?

Why would we want to do that? Doing so would mean that we wouldn't track any changes to `test_mReg.m` and the `CMakeLists.txt`, which we certainly want to do.

**Comment by rijobro** [comment]
ah sorry, i misread your comment. But anyway, the results of the ctest should go into your binary folder, so shouldn't be affected by the gitignore.

**Pull request merged**
