### PR TITLE
ImageData objects conversion tests (addresses issue #526).

### LINKED ISSUE #584: Operator == for ImageData conflicts with the one for NiftiImageData
@rijobro: I have implemented `operator==` for `ImageData`, but run into a conflict with the one in `NiftiImageData`: executing
```
nifti_image = NiftiImageData3D(image)
print(image == nifti_image)
``` 
where `image` is an `ImageData`, raises AssertionError in `NiftiImageData.__eq__` (which is bewildering as `ImageData.__eq__` should have been called).

I added `or isinstance(other, SIRF.ImageData)` in `NiftiImageData.__eq__`, but I got
```
'NiftiImageData<dataType>::are_equal_to_given_accuracy: Image 2 not initialised.' exception caught at line 360 of /home/sirfuser/devel/buildVM/sources/SIRF/src/Registration/cReg/cReg.cpp
```

If I comment out `NiftiImageData.__eq__` (which should be ok because I have `__eq__` in the base class), then the above problem disappears, and my Python ctests run ok, but `SYN_TEST_PYTHON` fails:
```
2:       Start 10: SYN_TEST_PYTHON
2: 10/10 Test #10: SYN_TEST_PYTHON .........................***Failed    1.89 sec
2: 
2: # --------------------------------------------------------------------------------- #
2: #                             Starting STIR to Nifti test...
2: # --------------------------------------------------------------------------------- #
2: 
2: WARNING: Unable to determine patient position. Internally this will generally be handled by assuming HFS
2: 
2: Saving image to file (results/stir_to_nifti.nii)...F
2: ======================================================================
2: FAIL: test_pSynergistic.test
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
2:     self.test(*self.arg)
2:   File "/home/sirfuser/devel/buildVM/sources/SIRF/src/Synergistic/tests/test_pSynergistic.py", line 209, in test
2:     try_stirtonifti(nifti_filename)
2:   File "/home/sirfuser/devel/buildVM/sources/SIRF/src/Synergistic/tests/test_pSynergistic.py", line 50, in try_stirtonifti
2:     raise AssertionError("Conversion from STIR to Nifti failed.")
2: AssertionError: Conversion from STIR to Nifti failed.
```

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
Adds simple `ImageData` conversion tests. Currently to `NiftiImageData` only, further work to be continued on master.

Also, quick-fixes #584 and #587.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
120 files changed? Most of them not related to what your describe above. What happened here?

**Comment by evgueni-ovtchinnikov** [comment]
I was working on this branch since mid-February, and I do not remember when was last time I merged master. Closing this PR for now and will resubmit after merging master.

**Comment by KrisThielemans** [comment]
might want to rebase then

**Comment by KrisThielemans** [comment]
also white-space issues in many files? not sure. Good luck! :-;

**Pull request closed without merging**
