### PR TITLE
include directory sirf/common in base CMakeLists

### PR DESCRIPTION
**Pull request by rijobro**
sirf/common is used throughout the code. makes sense to include it higher up, to avoid repetition.

### CODE REVIEW

**Comment by rijobro** [comment]
Any thoughts on this? There will at some point in the future be a folder for synergistic algorithms. They would need to access headers for Gadgetron, STIR, common, etc.

It seems to make sense to me to put `include_directories` for all sections, ie:
```
INCLUDE_DIRECTORIES(src/common/include)
INCLUDE_DIRECTORIES(src/iUtilities/include)
INCLUDE_DIRECTORIES(src/xSTIR/cSTIR/include)
INCLUDE_DIRECTORIES(src/xGadgetron/cGadgetron/include)
INCLUDE_DIRECTORIES(src/Registration/cReg/include)
```
In this way, all subdirectories of SIRF will be able to access all SIRF header files in different subdirectories elsewhere in the code.

**Comment by KrisThielemans** [comment]
Instead of doing this, we really should move to [target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html) for the libraries. That way, a user who says she needs the library, automatically gets the include file location. That'll also work once we install the include files. For instance, I think the following would be needed.
```
target_include_directories(common PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/>
  $<INSTALL_INTERFACE:include/
)
```
I'd drop this PR therefore, unless that causes problems for anyone who has merged it already...

**Comment by rijobro** [comment]
Ok. Similarly, synergistic code will need to access `${STIR_INCLUDE_DIRS}`, which is created in `src/xSTIR/CMakeLists.txt`. Presumably, this can also be included with `target_include_directories`?

**Comment by KrisThielemans** [comment]
can't remember if STIR uses this already, but it should...

**Comment by rijobro** [comment]
Ok.

**Pull request closed without merging**
