### PR TITLE
Use exam info when constructing VoxelsOnCartesianGrid

### PR DESCRIPTION
**Pull request by rijobro**
We were only using proj data info, but this does not store additional information, such as modality. Use a different STIR constructor that also accepts the exam info

### CODE REVIEW

**Comment by rijobro** [comment]
fixes #342.

**Comment by KrisThielemans** [comment]
Can you also set `imaging_modality` to "PET" in the `ExamInfo` here
https://github.com/CCPPETMR/SIRF/blob/8242f02392582e5201f04893102d230b3a19c20a/src/xSTIR/cSTIR/cstir.cpp#L532

**Comment by rijobro** [comment]
done

**Comment by rijobro** [comment]
any idea what's going on with Travis for this PR? https://api.travis-ci.org/v3/job/509915387/log.txt

```
Note: checking out '4e58810431b411c155d31920438e359ddcf7d854'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

fatal: reference is not a tree: bfe25ced998b4c7a6eaf47b1b4ffba9f18e1df1b
CMake Error at /home/travis/build/CCPPETMR/SIRF-SuperBuild/builds/SIRF/tmp/SIRF-gitclone.cmake:75 (message):
  Failed to checkout tag: 'bfe25ced998b4c7a6eaf47b1b4ffba9f18e1df1b'
```

**Comment by KrisThielemans** [comment]
no idea. Fine to merge for me (as long as you ran the tests locally)

**Pull request merged**
