### PR TITLE
add import sirf.Utilities to tests and minor clean-up

### LINKED ISSUE #317: tests fail when running only: need pUtilities
```
cd src/xSTIR/pSTIR/tests
python tests_four.py
```
gives
```
Traceback (most recent call last):
  File "tests_four.py", line 57, in <module>
    runner(test_main, __doc__, __version__, __author__)
NameError: name 'runner' is not defined
```
Running the test via `test_all.py` or `nose` does work fine

### PR DESCRIPTION
**Pull request by KrisThielemans**
- import sirf.Utilities Was missing which led to errors of
missing `runner` when run on its own. Fixes #317.
- replace pSTIR with sirf.STIR etc
- fix author list

### CODE REVIEW

**Comment by KrisThielemans** [comment]
works for me, but fails on Travis...

**Comment by KrisThielemans** [comment]
@casperdcl  I've renamed the modules from `pSTIR` to `sirf.STIR`. Build now works. Does this renaming matter for coverage?

I've had a look at https://coveralls.io/builds/22083302 but can't really see anything there.

**Comment by casperdcl** [comment]
looks like coverage results aren't being uploaded to coveralls...

**Comment by KrisThielemans** [comment]
coverage reported now, but still something wrong such that it's not useful (see [here](https://coveralls.io/builds/22090809/source?filename=/home/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/sirf/STIR.py))
```
Source Not Available

The file "/home/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/sirf/STIR.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.
```

**Comment by KrisThielemans** [comment]
Related posts: 
- https://bitbucket.org/ned/coveragepy/pull-requests/70/set-base-directory-for-relative-filenames/activity# (mentioning `[paths]` but I cannot find anything about that).
- https://github.com/lemurheavy/coveralls-public/issues/263

**Comment by casperdcl** [comment]
The problem is the python files are installed, rather than run from source. Perhaps we can go back to running from sources/SIRF rather than INSTALL/python?

**Comment by KrisThielemans** [comment]
No, I don't want to do that. Either we can adapt `.travis.yml` as in one of those links, or we forget about `coveralls` :-;

**Comment by casperdcl** [comment]
also `codecov`. Probably best to do as with the links.

Could also probably run a simple find&replace on the generated coverage reports to change the paths before uploading.

**Comment by casperdcl** [comment]
fixes #320

**Pull request merged**
