### PR TITLE
zenodo: more author metadata, and ccp-petmr community

### PR DESCRIPTION
**Pull request by casperdcl**
- add Zenodo metadata for automated release (https://doi.org/10.5281/zenodo.2707911)
  - list of authors, ORCIDs, affiliations
  - communities: [CCP-PETMR](https://zenodo.org/communities/ccp-petmr)
  - licence: ~~[Apache-2.0](https://spdx.org/licenses/Apache-2.0.html)~~ Other (for now, until GPL from FFTW is removed)
  - related DOI: [10.1109/NSSMIC.2017.8532815](https://doi.org/10.1109/NSSMIC.2017.8532815)

### CODE REVIEW

**Comment by casperdcl** [comment]
@KrisThielemans regarding `foobar2016` previously appearing in Zenodo:

1. it's no longer an issue if we're specifying authors in a metadata file
2. apparently it's likely because a contributor used to have that username

**Comment by ashgillman** [comment]
Unrelated, but how did Johannes get an 'X' in his ORCID? I checked and it links correctly.

**Comment by casperdcl** [comment]
lol I noticed that

**Comment by casperdcl** [comment]
response from Zenodo support:

> You can see the code that does the extraction here: https://github.com/inveniosoftware/invenio-github/blob/master/invenio_github/utils.py#L80-L108 
>
> I've tried to debug it, and I've traced the foobar2016 to this GitHub API response:
>
> https://api.github.com/repos/CCPPETMR/SIRF/stats/contributors (https://developer.github.com/v3/repos/#list-contributors)
> forbar2016 is listed there as having 3 contributions to the project
>
> How the user ended up there I didn't have time to look into yet.

**Comment by KrisThielemans** [comment]
Currently, our license still has to be GPL 3 due to use of FFTW. can we say something like "GPL 3, but most parts also licensed as Apache 2.0"?

**Comment by KrisThielemans** [comment]
@casperdcl I actually cannot see `foobar2016` on our list of contributors. (Indeed, that user has no contributions to any repo anywhere). mystery.

**Comment by casperdcl** [comment]
> can we say something like "GPL 3, but most parts also licensed as Apache 2.0"?

no but we can leave it as the default (Other - Open)

> I actually cannot see `foobar2016` on our list of contributors

good point, neither can I when I access the API. Sent a follow-up to Zenodo. They must have some weird caching issues.

**Comment by ashgillman** [comment]
NB: You might have to accept  #392 before this PR

**Comment by rijobro** [comment]
> NB: You might have to accept #392 before this PR

Good spot, done.

**Comment by casperdcl** [comment]
@paskino you may want to check this file to find out author details

**Comment by casperdcl** [comment]
Follow-up from Zenodo:

> I apologise, I sent the wrong [...] URL. The URL is https://api.github.com/repos/CCPPETMR/SIRF/contributors (without stats) [...] which includes `foobar2016`.
> 
> [...] you can see the commits here:
> https://api.github.com/repos/CCPPETMR/SIRF/commits?author=foobar2016 
> Specifically [...]:
> ddc363c2ac81076e533e8696d838f9d01bf82bd2
> 18b7e18ac8dc293c90b9e136f006fa993cb85b5d
> 819d8a12e7c5b3ab3d7e053c98d3796925dec2fb
> [...] authored by:
> Evgueni Ovtchinnikov <<me@example.com>>
> 
> Why GitHub is associating the GitHub user `foobar2016` with Evgueni Ovtchinnikov <<me@example.com>>, I don't know. Perhaps because of the email address "me@example.com" being used?

**Comment by ashgillman** [comment]
Some quick edits on a cluster or another computer perhaps?

I've had similar experiences when making edits on the cluster and no email was set, GitHub doesn't associate the commits with my account.

You can modify these with
`git config --global user.email "me@example.com"` and also `user.name`.

**Comment by KrisThielemans** [comment]
my first thought was that github is a bit silly but I then realised that the commiter email is probably the only way they can do this. After all, you can have lots of local commits made by lots of different people, which then one github user pushes. Those commits should not be assigned to the github user of course. Therefore, github has to look at git content, which stores `user.email` and `user.name` for each commit. Makes sense.

We cannot fix this as it'd mean invalidating all commits since then (replacing them with new ones), so we'll live with it.

Moral of the store: be careful how you do your `git config`!

@casperdcl please thank your zenodo contact. Very helpful!

**Pull request merged**
