### PR TITLE
Remove ismrmrd dependency in sirf/common

### PR DESCRIPTION
**Pull request by rijobro**
Remove ismrmrd dependency in sirf/common

### CODE REVIEW

**Comment by KrisThielemans** [comment]
thanks. definitely a good idea to be independent of ISMRMRD.

I agree with @bathomas, we should drop ISMRMRD from the name. There doesn't seem to be any point in adding `SIRF` as it's already in the `sirf` namespace. I vote for `enum class NumberType`  (`DataType` seems to general to me). It then probably needs to be in its own header as I guess @rijobro will want to use it for SIRFReg (or has it already...)

**Comment by rijobro** [comment]
Apparently I can't use a strongly typed `enum`, because the following switch is used:
```
switch (type_) {
    case NumberType::CXDOUBLE:
...
```
where `type_` is an `int`. This can't be done as strongly typed `enum`s can't be converted to `int`s. Are you happy with me using `enum NumberType` instead of `enum class NumberType`?

**Comment by rijobro** [comment]
Done.

**Comment by KrisThielemans** [comment]
of course, a merge is also fine (depending on what @rijobro wants)

**Comment by rijobro** [comment]
Not fussed either way. Whatever the git gurus decided!

**Comment by KrisThielemans** [comment]
if not merged elsewhere, squash merge. it's a small change. one commit would do the trick

**Comment by evgueni-ovtchinnikov** [comment]
all travis builds failed with the message

fatal: Authentication failed for 'https://@github.com/ccp-petmr-codebot/github-stats/'

**Pull request merged**
