### PR TITLE
sirf python packaging

### PR DESCRIPTION
**Pull request by casperdcl**
migrated from https://github.com/CCPPETMR/SIRF-SuperBuild/pull/109

- [x] provides `setup.py`
    + [x] provides `sirf`
    + [x] alias for backward-compatibility
        * [x] `p(Gadgetron|STIR|Utilities)` to `sirf.p(Gadgetron|STIR|Utilities)`
        * [x] `py(gadgetron|stir|iutilities)` to `sirf.py(gadgetron|stir|iutilities)`
        + [x] remove `p` (`sirf.`~~`p`~~`(Gadgetron|STIR|Utilities)`)
        + ~~remove `py` (`sirf.`~~`py`~~`(gadgetron|stir|iutilities)`)?~~
- [x] cmake -> ~~pip install ->~~ setup.py
    + [x] expose `PYTHON_STRATEGY` (`CONDA|SETUP_PY|PYTHONPATH`)
- ~~depends on #160 (for now uses #161)~~
    + no longer depends because installation based on `PYTHON_STRATEGY` is migrated here
- [x] register `sirf` on `PyPI` before anyone else does (https://pypi.org/project/sirf/)

## old

- `${PYTHON_DEST}/`
    + `*.(py|so)`

## new

- `${PYTHON_DEST}/`
    + `setup.py`
    + `sirf/`
        * `__init__.py`
        * `*.(py|so)`
    + `p*/__init__.py`

## future

- [ ] (ana)conda @paskino
- [ ] register `sirf` on `conda-forge`
- [ ] `setup.py:build_ext` to call `cmake` @casperdcl
    + https://stackoverflow.com/a/48015772/3896283
    + won't need to re-implement `cmake` call in `conda`
    + will need to pass `cmake` build args to `setup.py` (pretty easy)

### CODE REVIEW

**Comment by casperdcl** [comment]
This PR has no dependencies, and I've tested it and it's all fine. mergeable as-is.

@KrisThielemans , regarding dropping `p`/`py`, this would require renaming the actual libraries built by swig. Is that OK? Also, did we want to drop `py`, or just `p`?

**Comment by casperdcl** [comment]
problems with renaming:

- remove `p` (`sirf.`~~`p`~~`(Gadgetron|STIR|Utilities)`)
- remove `py` (`sirf.`~~`py`~~`(gadgetron|stir|iutilities)`)

1. will create e.g. `Gadgetron.py` and `gadgetron.py` in the same directory, which would cause problems on windows (case-insensitive filenames conflict)
2. will have issues renaming the swig module `pyiutilities` -> `iutilities` since `iutilities` already exists as a target library which other things link to

**Comment by evgueni-ovtchinnikov** [comment]
@casperdcl  @KrisThielemans 
remove p but not py - looks ok to me

**Comment by KrisThielemans** [comment]
yes. that looks fine. I believe the `py*` are "internal".  In principle they could even be hidden from the user I think. @evgueni-ovtchinnikov, correct?

**Pull request merged**
